"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["main.py"]
DATA_FILES = []
OPTIONS = {"iconfile": "icon.png", "emulate_shell_environment": True}

setup(
    app=APP,
    name="video-dl",
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
