
SET RES_NUM=0

:: 1:1
REM SET /A RES_NUM=RES_NUM+1
REM SET RES_W[%RES_NUM%]=256
REM SET RES_H[%RES_NUM%]=256
REM SET /A RES_NUM=RES_NUM+1
REM SET RES_W[%RES_NUM%]=512
REM SET RES_H[%RES_NUM%]=512
REM SET /A RES_NUM=RES_NUM+1
REM SET RES_W[%RES_NUM%]=1024
REM SET RES_H[%RES_NUM%]=1024
REM SET /A RES_NUM=RES_NUM+1
REM SET RES_W[%RES_NUM%]=2048
REM SET RES_H[%RES_NUM%]=2048

:: 4:3
REM SET /A RES_NUM=RES_NUM+1
REM SET RES_W[%RES_NUM%]=320
REM SET RES_H[%RES_NUM%]=240
REM SET /A RES_NUM=RES_NUM+1
REM SET RES_W[%RES_NUM%]=480
REM SET RES_H[%RES_NUM%]=360
REM SET /A RES_NUM=RES_NUM+1
REM SET RES_W[%RES_NUM%]=640
REM SET RES_H[%RES_NUM%]=480
REM SET /A RES_NUM=RES_NUM+1
REM SET RES_W[%RES_NUM%]=800
REM SET RES_H[%RES_NUM%]=600
REM SET /A RES_NUM=RES_NUM+1
REM SET RES_W[%RES_NUM%]=1024
REM SET RES_H[%RES_NUM%]=768
REM SET /A RES_NUM=RES_NUM+1
REM SET RES_W[%RES_NUM%]=1600
REM SET RES_H[%RES_NUM%]=1200

:: 5:4
REM SET /A RES_NUM=RES_NUM+1
REM SET RES_W[%RES_NUM%]=1152
REM SET RES_H[%RES_NUM%]=864
REM SET /A RES_NUM=RES_NUM+1
REM SET RES_W[%RES_NUM%]=1280
REM SET RES_H[%RES_NUM%]=1024

:: 16:9
REM SET /A RES_NUM=RES_NUM+1
REM SET RES_W[%RES_NUM%]=426
REM SET RES_H[%RES_NUM%]=240
REM SET /A RES_NUM=RES_NUM+1
REM SET RES_W[%RES_NUM%]=640
REM SET RES_H[%RES_NUM%]=360
REM SET /A RES_NUM=RES_NUM+1
REM SET RES_W[%RES_NUM%]=854
REM SET RES_H[%RES_NUM%]=480
REM SET /A RES_NUM=RES_NUM+1
REM SET RES_W[%RES_NUM%]=960
REM SET RES_H[%RES_NUM%]=540
REM SET /A RES_NUM=RES_NUM+1
REM SET RES_W[%RES_NUM%]=1280
REM SET RES_H[%RES_NUM%]=720
REM SET /A RES_NUM=RES_NUM+1
REM SET RES_W[%RES_NUM%]=1366
REM SET RES_H[%RES_NUM%]=768
SET /A RES_NUM=RES_NUM+1
SET RES_W[%RES_NUM%]=1920
SET RES_H[%RES_NUM%]=1080
REM SET /A RES_NUM=RES_NUM+1
REM SET RES_W[%RES_NUM%]=2560
REM SET RES_H[%RES_NUM%]=1440
REM SET /A RES_NUM=RES_NUM+1
REM SET RES_W[%RES_NUM%]=3840
REM SET RES_H[%RES_NUM%]=2160

:: 16:10
REM SET /A RES_NUM=RES_NUM+1
REM SET RES_W[%RES_NUM%]=1280
REM SET RES_H[%RES_NUM%]=800
REM SET /A RES_NUM=RES_NUM+1
REM SET RES_W[%RES_NUM%]=1440
REM SET RES_H[%RES_NUM%]=900
REM SET /A RES_NUM=RES_NUM+1
REM SET RES_W[%RES_NUM%]=1920
REM SET RES_H[%RES_NUM%]=1200

exit /B
