name: Static analysis check

on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install mypy and stubs
      run: |
        pip install mypy types-requests
    - name: Intall project dependencies
      run: |
        pip install -r requirements.txt
    - name: Run mypy
      run: |
        mypy *.py --ignore-missing-imports
